### ISSUE TITLE
hard-coded lang strings

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#10]
https://github.com/skillsoftadmin/moodle-mod_percipio/blob/master/launch.php#L113

please note - all user facing strings need to be contained within the lang strings - this is also a blocker for approval.

**Comment by skillsoftadmin** [comment]
Hello Dan,
We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. 
Thank you.
