### ISSUE TITLE
score.php file mixes inline php code and classes

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#11]
Class files should be in standalone php files within the classes folder in your code. Please note that we also have naming conventions for functions/classes that need to be followed as per:
https://docs.moodle.org/dev/Frankenstyle

Please do not mix inline php code with classes (or functions)

**Comment by skillsoftadmin** [comment]
Hello Dan,
We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. 
Thank you.
