### ISSUE TITLE
Please review use of PARAM_RAW

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#12]
PARAM_RAW does no cleaning - I see a few places where it's used for storing various things that should not require scripts or html to be passed - things like urls, secrets should not need to use PARAM_RAW at all.

**Comment by skillsoftadmin** [comment]
Hello Dan,
We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. 
Thank you.
