### ISSUE TITLE
function naming violations

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#13]
please follow our naming rules for functions within your plugin - classes must be namespaced correctly, but standalone functions must use the plugin name as a prefix eg:
https://github.com/skillsoftadmin/moodle-mod_percipio/blob/master/lib.php#L360

That function could clash with core functions so should be prefixed with "percipio" - for more info on naming conventions see:
https://docs.moodle.org/dev/Frankenstyle

please note this is a blocker for approval.

**Comment by skillsoftadmin** [comment]
Hello Dan,
We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. 
Thank you.
