### ISSUE TITLE
please do not call curl_init directly

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#14]
Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

Many organisations put their moodle site behind a web proxy and the internal curl wrapper takes care of this for you.

**Comment by skillsoftadmin** [comment]
Hello Dan,
We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. 
Thank you.
