### ISSUE TITLE
don't need "moodle1" backup folder

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#16]
you could just delete the "backups/moodle1" folder - I'm assuming you've copied it from one of the other core plugins.

that folder allows moodle backups prior to Moodle 2.0 to be restored into a site, but you have never supported Moodle 1.9 or earlier in your plugin, so there won't be any backups around that old :-)

**Comment by skillsoftadmin** [comment]
Hi Dan, we have made the changes, request you to review again.
Thank you for your valuable feedback!
