### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#2]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin stores user data in a number of tables which will need to be included in the privaci api classes.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

Please note - as your plugin passes data to an external api you must also implement the add_external_location_link component of the privacy api:
https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

Please note - this is a blocker for approval in the plugins db.

**Comment by skillsoftadmin** [comment]
Hello Dan,
We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. 
Thank you.
