### ISSUE TITLE
date handling should use probably use userdate() function

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#20]
Some languages have specific requirements for displaying times - and users can set their own timezone - ideally when displaying dates, this should be taken into account using the "userdate" function

eg:
https://github.com/skillsoftadmin/moodle-mod_percipio/blob/master/classes/percipio_table.php#L47

if you do a search on "function col_timemodified" in the moodle core code, you'll see a few different ways this is implemented.

**Comment by skillsoftadmin** [comment]
Hi Dan, we have incorporated this suggestion.
Thank you :)
