### ISSUE TITLE
Missing activity backup api

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#3]
Activity plugins must implement the backup/restore api more info see here:
https://docs.moodle.org/dev/Backup_API

please note this is a blocker for plugins db approval.

**Comment by skillsoftadmin** [comment]
Hello Dan,
We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. 
Thank you.
