### ISSUE TITLE
Incorrect camel case in strings

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#5]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

**Comment by skillsoftadmin** [comment]
Hello Dan,
We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. 
Thank you.
