### ISSUE TITLE
direct access to $_POST/$_GET/$_REQUEST not allowed

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#6]
eg:
https://github.com/skillsoftadmin/moodle-mod_percipio/blob/master/score.php#L30

Please use Moodle's optional/required_param functions - direct access to those globals is a violation of our security guidelines (and a blocker for approval)

more info see:
https://docs.moodle.org/dev/Security#Summary_of_the_guidelines

**Comment by skillsoftadmin** [comment]
Hello Dan,
We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. 
Thank you.
