### ISSUE TITLE
missing capability and login checks in custom web services.

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#7]
The custom web services you have implemented do not perform any login or capability checks - defining them in the function array is not enough:
https://github.com/skillsoftadmin/moodle-mod_percipio/blob/master/db/services.php#L34

you MUST add login and capability checks to the web service functions themselves - for example this function doesn't check if the current user is logged in, or if the user can actually peform any of the tasks in the file - it needs a login and capability check at the top.

https://github.com/skillsoftadmin/moodle-mod_percipio/blob/master/externallib.php#L66

you should check your other custom webservices and look at core Moodle webservice functions for example on how to do this.

**Comment by skillsoftadmin** [comment]
Hello Dan,
We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. 
Thank you.
